import type { AssetTemplate } from '@/types'

const fbPost: AssetTemplate = {
  id: 'fb-post',
  name: 'Facebook Post',
  platform: 'facebook',
  format: 'post',
  width: 1200,
  height: 630,
  variants: [
    {
      id: 'centered',
      name: 'Centered',
      defaultAlign: 'center',
      elements: [
        {
          type: 'artwork',
          position: { x: 400, y: 80, anchor: 'top-left' },
          size: { width: 400, height: 400 },
          style: { borderRadius: 10 },
        },
        {
          type: 'gradient',
          position: { x: 0, y: 0, anchor: 'top-left' },
          size: { width: 1200, height: 630 },
          style: { opacity: 0.65, direction: 180 },
        },
        {
          type: 'text',
          position: { x: 600, y: 20, anchor: 'top-center' },
          size: { width: 200, height: 20 },
          style: { fontSize: 14, fontWeight: 'regular', textAlign: 'center', opacity: 0.5, letterSpacing: 3 },
          content: '{{musicType}}',
          toggleable: true,
          visible: true,
        },
        {
          type: 'text',
          position: { x: 600, y: 520, anchor: 'bottom-center' },
          size: { width: 800, height: 48 },
          style: { fontSize: 42, fontWeight: 'black', textAlign: 'center' },
          content: '{{title}}',
        },
        {
          type: 'text',
          position: { x: 600, y: 575, anchor: 'bottom-center' },
          size: { width: 800, height: 36 },
          style: { fontSize: 30, fontWeight: 'bold', textAlign: 'center' },
          content: '{{artistName}}',
          toggleable: true,
          visible: true,
        },
        {
          type: 'text',
          position: { x: 600, y: 610, anchor: 'bottom-center' },
          size: { width: 500, height: 28 },
          style: { fontSize: 22, fontWeight: 'regular', textAlign: 'center', opacity: 0.8 },
          content: '{{releaseDate}}',
          toggleable: true,
          visible: true,
        },
      ],
    },
    {
      id: 'editorial',
      name: 'Editorial',
      defaultAlign: 'center',
      elements: [
        {
          type: 'artwork',
          position: { x: 0, y: 0, anchor: 'top-left' },
          size: { width: 630, height: 630 },
          style: { objectFit: 'cover' },
        },
        {
          type: 'gradient',
          position: { x: 630, y: 0, anchor: 'top-left' },
          size: { width: 570, height: 630 },
          style: { opacity: 1, direction: 135 },
        },
        {
          type: 'text',
          position: { x: 915, y: 170, anchor: 'center' },
          size: { width: 200, height: 20 },
          style: { fontSize: 14, fontWeight: 'regular', textAlign: 'center', opacity: 0.5, letterSpacing: 3 },
          content: '{{musicType}}',
          toggleable: true,
          visible: true,
        },
        {
          type: 'text',
          position: { x: 915, y: 230, anchor: 'center' },
          size: { width: 480, height: 52 },
          style: { fontSize: 44, fontWeight: 'black', textAlign: 'center' },
          content: '{{title}}',
        },
        {
          type: 'text',
          position: { x: 915, y: 305, anchor: 'center' },
          size: { width: 480, height: 36 },
          style: { fontSize: 28, fontWeight: 'bold', textAlign: 'center' },
          content: '{{artistName}}',
          toggleable: true,
          visible: true,
        },
        {
          type: 'text',
          position: { x: 915, y: 360, anchor: 'center' },
          size: { width: 400, height: 28 },
          style: { fontSize: 22, fontWeight: 'regular', textAlign: 'center', opacity: 0.8 },
          content: '{{releaseDate}}',
          toggleable: true,
          visible: true,
        },
      ],
    },
    {
      id: 'split',
      name: 'Split',
      defaultAlign: 'center',
      elements: [
        {
          type: 'artwork',
          position: { x: 0, y: 0, anchor: 'top-left' },
          size: { width: 1200, height: 320 },
          style: { objectFit: 'cover' },
        },
        {
          type: 'gradient',
          position: { x: 0, y: 320, anchor: 'top-left' },
          size: { width: 1200, height: 310 },
          style: { opacity: 1, direction: 180 },
        },
        {
          type: 'text',
          position: { x: 600, y: 400, anchor: 'center' },
          size: { width: 200, height: 20 },
          style: { fontSize: 14, fontWeight: 'regular', textAlign: 'center', opacity: 0.5, letterSpacing: 3 },
          content: '{{musicType}}',
          toggleable: true,
          visible: true,
        },
        {
          type: 'text',
          position: { x: 600, y: 450, anchor: 'center' },
          size: { width: 1000, height: 48 },
          style: { fontSize: 40, fontWeight: 'black', textAlign: 'center' },
          content: '{{title}}',
        },
        {
          type: 'text',
          position: { x: 600, y: 515, anchor: 'center' },
          size: { width: 800, height: 32 },
          style: { fontSize: 26, fontWeight: 'bold', textAlign: 'center' },
          content: '{{artistName}}',
          toggleable: true,
          visible: true,
        },
        {
          type: 'text',
          position: { x: 600, y: 565, anchor: 'center' },
          size: { width: 500, height: 26 },
          style: { fontSize: 20, fontWeight: 'regular', textAlign: 'center', opacity: 0.8 },
          content: '{{releaseDate}}',
          toggleable: true,
          visible: true,
        },
      ],
    },
    {
      id: 'minimal',
      name: 'Minimal',
      defaultAlign: 'left',
      elements: [
        {
          type: 'artwork',
          position: { x: 60, y: 140, anchor: 'top-left' },
          size: { width: 350, height: 350 },
          style: { borderRadius: 8 },
        },
        {
          type: 'gradient',
          position: { x: 0, y: 0, anchor: 'top-left' },
          size: { width: 1200, height: 630 },
          style: { opacity: 0.4, direction: 90 },
        },
        {
          type: 'text',
          position: { x: 490, y: 120, anchor: 'top-left' },
          size: { width: 200, height: 20 },
          style: { fontSize: 14, fontWeight: 'regular', textAlign: 'left', opacity: 0.5, letterSpacing: 3 },
          content: '{{musicType}}',
          toggleable: true,
          visible: true,
        },
        {
          type: 'text',
          position: { x: 490, y: 160, anchor: 'top-left' },
          size: { width: 640, height: 48 },
          style: { fontSize: 42, fontWeight: 'black', textAlign: 'left' },
          content: '{{title}}',
        },
        {
          type: 'text',
          position: { x: 490, y: 225, anchor: 'top-left' },
          size: { width: 640, height: 34 },
          style: { fontSize: 28, fontWeight: 'bold', textAlign: 'left' },
          content: '{{artistName}}',
          toggleable: true,
          visible: true,
        },
        {
          type: 'text',
          position: { x: 490, y: 270, anchor: 'top-left' },
          size: { width: 400, height: 26 },
          style: { fontSize: 20, fontWeight: 'regular', textAlign: 'left', opacity: 0.7 },
          content: '{{releaseDate}}',
          toggleable: true,
          visible: true,
        },
      ],
    },
    {
      id: 'full-bleed',
      name: 'Full Bleed',
      defaultAlign: 'center',
      elements: [
        {
          type: 'artwork',
          position: { x: 0, y: 0, anchor: 'top-left' },
          size: { width: 1200, height: 630 },
          style: { objectFit: 'cover' },
        },
        {
          type: 'gradient',
          position: { x: 0, y: 210, anchor: 'top-left' },
          size: { width: 1200, height: 420 },
          style: { opacity: 0.9, direction: 180 },
        },
        {
          type: 'text',
          position: { x: 600, y: 390, anchor: 'center' },
          size: { width: 200, height: 20 },
          style: { fontSize: 14, fontWeight: 'regular', textAlign: 'center', opacity: 0.5, letterSpacing: 3 },
          content: '{{musicType}}',
          toggleable: true,
          visible: true,
        },
        {
          type: 'text',
          position: { x: 600, y: 445, anchor: 'center' },
          size: { width: 1000, height: 52 },
          style: { fontSize: 46, fontWeight: 'black', textAlign: 'center' },
          content: '{{title}}',
        },
        {
          type: 'text',
          position: { x: 600, y: 520, anchor: 'center' },
          size: { width: 1000, height: 36 },
          style: { fontSize: 30, fontWeight: 'bold', textAlign: 'center' },
          content: '{{artistName}}',
          toggleable: true,
          visible: true,
        },
        {
          type: 'text',
          position: { x: 600, y: 575, anchor: 'center' },
          size: { width: 500, height: 26 },
          style: { fontSize: 20, fontWeight: 'regular', textAlign: 'center', opacity: 0.8 },
          content: '{{releaseDate}}',
          toggleable: true,
          visible: true,
        },
      ],
    },
  ],
}

export default fbPost
