import type { AssetTemplate } from '@/types'

const igPortrait: AssetTemplate = {
  id: 'ig-portrait',
  name: 'Instagram Portrait',
  platform: 'instagram',
  format: 'portrait',
  width: 1080,
  height: 1350,
  variants: [
    {
      id: 'centered',
      name: 'Centered',
      defaultAlign: 'center',
      elements: [
        {
          type: 'artwork',
          position: { x: 190, y: 110, anchor: 'top-center' },
          size: { width: 700, height: 700 },
          style: { borderRadius: 12 },
        },
        {
          type: 'gradient',
          position: { x: 0, y: 0, anchor: 'top-left' },
          size: { width: 1080, height: 1350 },
          style: { opacity: 0.6, direction: 180 },
        },
        {
          type: 'text',
          position: { x: 540, y: 880, anchor: 'top-center' },
          size: { width: 900, height: 24 },
          style: { fontSize: 16, fontWeight: 'regular', textAlign: 'center', opacity: 0.5, letterSpacing: 3 },
          content: '{{musicType}}',
          toggleable: true,
          visible: true,
        },
        {
          type: 'text',
          position: { x: 540, y: 923, anchor: 'top-center' },
          size: { width: 900, height: 60 },
          style: { fontSize: 54, fontWeight: 'black', textAlign: 'center' },
          content: '{{title}}',
        },
        {
          type: 'text',
          position: { x: 540, y: 995, anchor: 'top-center' },
          size: { width: 900, height: 50 },
          style: { fontSize: 44, fontWeight: 'bold', textAlign: 'center' },
          content: '{{artistName}}',
          toggleable: true,
          visible: true,
        },
        {
          type: 'text',
          position: { x: 540, y: 1055, anchor: 'top-center' },
          size: { width: 600, height: 34 },
          style: { fontSize: 28, fontWeight: 'regular', textAlign: 'center', opacity: 0.8 },
          content: '{{releaseDate}}',
          toggleable: true,
          visible: true,
        },
      ],
    },
    {
      id: 'bottom-aligned',
      name: 'Bottom-aligned',
      defaultAlign: 'left',
      elements: [
        {
          type: 'artwork',
          position: { x: 0, y: 0, anchor: 'top-left' },
          size: { width: 1080, height: 1350 },
          style: { objectFit: 'cover' },
        },
        {
          type: 'gradient',
          position: { x: 0, y: 675, anchor: 'top-left' },
          size: { width: 1080, height: 675 },
          style: { opacity: 0.85, direction: 180 },
        },
        {
          type: 'text',
          position: { x: 60, y: 975, anchor: 'top-left' },
          size: { width: 960, height: 24 },
          style: { fontSize: 16, fontWeight: 'regular', textAlign: 'left', opacity: 0.5, letterSpacing: 3 },
          content: '{{musicType}}',
          toggleable: true,
          visible: true,
        },
        {
          type: 'text',
          position: { x: 60, y: 1017, anchor: 'top-left' },
          size: { width: 960, height: 64 },
          style: { fontSize: 58, fontWeight: 'black', textAlign: 'left' },
          content: '{{title}}',
        },
        {
          type: 'text',
          position: { x: 60, y: 1095, anchor: 'top-left' },
          size: { width: 960, height: 48 },
          style: { fontSize: 40, fontWeight: 'bold', textAlign: 'left' },
          content: '{{artistName}}',
          toggleable: true,
          visible: true,
        },
        {
          type: 'text',
          position: { x: 60, y: 1155, anchor: 'top-left' },
          size: { width: 600, height: 34 },
          style: { fontSize: 28, fontWeight: 'regular', textAlign: 'left', opacity: 0.8 },
          content: '{{releaseDate}}',
          toggleable: true,
          visible: true,
        },
      ],
    },
    {
      id: 'split',
      name: 'Split',
      defaultAlign: 'center',
      elements: [
        {
          type: 'artwork',
          position: { x: 0, y: 0, anchor: 'top-left' },
          size: { width: 1080, height: 675 },
          style: { objectFit: 'cover' },
        },
        {
          type: 'gradient',
          position: { x: 0, y: 675, anchor: 'top-left' },
          size: { width: 1080, height: 675 },
          style: { opacity: 1, direction: 180 },
        },
        {
          type: 'text',
          position: { x: 540, y: 800, anchor: 'top-center' },
          size: { width: 960, height: 24 },
          style: { fontSize: 16, fontWeight: 'regular', textAlign: 'center', opacity: 0.5, letterSpacing: 3 },
          content: '{{musicType}}',
          toggleable: true,
          visible: true,
        },
        {
          type: 'text',
          position: { x: 540, y: 840, anchor: 'top-center' },
          size: { width: 960, height: 64 },
          style: { fontSize: 58, fontWeight: 'black', textAlign: 'center' },
          content: '{{title}}',
        },
        {
          type: 'text',
          position: { x: 540, y: 920, anchor: 'top-center' },
          size: { width: 960, height: 48 },
          style: { fontSize: 40, fontWeight: 'bold', textAlign: 'center' },
          content: '{{artistName}}',
          toggleable: true,
          visible: true,
        },
        {
          type: 'text',
          position: { x: 540, y: 980, anchor: 'top-center' },
          size: { width: 600, height: 34 },
          style: { fontSize: 28, fontWeight: 'regular', textAlign: 'center', opacity: 0.8 },
          content: '{{releaseDate}}',
          toggleable: true,
          visible: true,
        },
      ],
    },
    {
      id: 'minimal',
      name: 'Minimal',
      defaultAlign: 'center',
      elements: [
        {
          type: 'artwork',
          position: { x: 290, y: 200, anchor: 'top-center' },
          size: { width: 500, height: 500 },
          style: { borderRadius: 8 },
        },
        {
          type: 'gradient',
          position: { x: 0, y: 0, anchor: 'top-left' },
          size: { width: 1080, height: 1350 },
          style: { opacity: 0.35, direction: 180 },
        },
        {
          type: 'text',
          position: { x: 540, y: 815, anchor: 'top-center' },
          size: { width: 800, height: 24 },
          style: { fontSize: 16, fontWeight: 'regular', textAlign: 'center', opacity: 0.5, letterSpacing: 3 },
          content: '{{musicType}}',
          toggleable: true,
          visible: true,
        },
        {
          type: 'text',
          position: { x: 540, y: 860, anchor: 'top-center' },
          size: { width: 800, height: 70 },
          style: { fontSize: 60, fontWeight: 'black', textAlign: 'center' },
          content: '{{title}}',
        },
        {
          type: 'text',
          position: { x: 540, y: 943, anchor: 'top-center' },
          size: { width: 800, height: 50 },
          style: { fontSize: 42, fontWeight: 'bold', textAlign: 'center' },
          content: '{{artistName}}',
          toggleable: true,
          visible: true,
        },
        {
          type: 'text',
          position: { x: 540, y: 1005, anchor: 'top-center' },
          size: { width: 600, height: 34 },
          style: { fontSize: 26, fontWeight: 'regular', textAlign: 'center', opacity: 0.7 },
          content: '{{releaseDate}}',
          toggleable: true,
          visible: true,
        },
      ],
    },
  ],
}

export default igPortrait
