import type { AssetTemplate } from '@/types'

const igStory: AssetTemplate = {
  id: 'ig-story',
  name: 'Instagram Story',
  platform: 'instagram',
  format: 'story',
  width: 1080,
  height: 1920,
  variants: [
    {
      id: 'top-heavy',
      name: 'Top-heavy',
      defaultAlign: 'center',
      elements: [
        {
          type: 'artwork',
          position: { x: 90, y: 120, anchor: 'top-center' },
          size: { width: 900, height: 900 },
          style: { borderRadius: 16 },
        },
        {
          type: 'gradient',
          position: { x: 0, y: 0, anchor: 'top-left' },
          size: { width: 1080, height: 1920 },
          style: { opacity: 0.5, direction: 180 },
        },
        {
          type: 'text',
          position: { x: 540, y: 1200, anchor: 'top-center' },
          size: { width: 600, height: 28 },
          style: { fontSize: 18, fontWeight: 'regular', textAlign: 'center', opacity: 0.5, letterSpacing: 3 },
          content: '{{musicType}}',
          toggleable: true,
          visible: true,
        },
        {
          type: 'text',
          position: { x: 540, y: 1245, anchor: 'top-center' },
          size: { width: 920, height: 72 },
          style: { fontSize: 64, fontWeight: 'black', textAlign: 'center' },
          content: '{{title}}',
        },
        {
          type: 'text',
          position: { x: 540, y: 1330, anchor: 'top-center' },
          size: { width: 920, height: 52 },
          style: { fontSize: 44, fontWeight: 'bold', textAlign: 'center' },
          content: '{{artistName}}',
          toggleable: true,
          visible: true,
        },
        {
          type: 'text',
          position: { x: 540, y: 1400, anchor: 'top-center' },
          size: { width: 600, height: 36 },
          style: { fontSize: 28, fontWeight: 'regular', textAlign: 'center', opacity: 0.8 },
          content: '{{releaseDate}}',
          toggleable: true,
          visible: true,
        },
      ],
    },
    {
      id: 'centered',
      name: 'Centered',
      defaultAlign: 'center',
      elements: [
        {
          type: 'artwork',
          position: { x: 180, y: 200, anchor: 'top-left' },
          size: { width: 720, height: 720 },
          style: { borderRadius: 12 },
        },
        {
          type: 'gradient',
          position: { x: 0, y: 0, anchor: 'top-left' },
          size: { width: 1080, height: 1920 },
          style: { opacity: 0.6, direction: 180 },
        },
        {
          type: 'text',
          position: { x: 540, y: 1160, anchor: 'top-center' },
          size: { width: 600, height: 28 },
          style: { fontSize: 18, fontWeight: 'regular', textAlign: 'center', opacity: 0.5, letterSpacing: 3 },
          content: '{{musicType}}',
          toggleable: true,
          visible: true,
        },
        {
          type: 'text',
          position: { x: 540, y: 1205, anchor: 'top-center' },
          size: { width: 920, height: 72 },
          style: { fontSize: 64, fontWeight: 'black', textAlign: 'center' },
          content: '{{title}}',
        },
        {
          type: 'text',
          position: { x: 540, y: 1290, anchor: 'top-center' },
          size: { width: 920, height: 52 },
          style: { fontSize: 44, fontWeight: 'bold', textAlign: 'center' },
          content: '{{artistName}}',
          toggleable: true,
          visible: true,
        },
        {
          type: 'text',
          position: { x: 540, y: 1360, anchor: 'top-center' },
          size: { width: 600, height: 36 },
          style: { fontSize: 28, fontWeight: 'regular', textAlign: 'center', opacity: 0.8 },
          content: '{{releaseDate}}',
          toggleable: true,
          visible: true,
        },
      ],
    },
    {
      id: 'bottom',
      name: 'Bottom',
      defaultAlign: 'left',
      elements: [
        {
          type: 'artwork',
          position: { x: 0, y: 0, anchor: 'top-left' },
          size: { width: 1080, height: 1920 },
          style: { objectFit: 'cover' },
        },
        {
          type: 'gradient',
          position: { x: 0, y: 960, anchor: 'top-left' },
          size: { width: 1080, height: 960 },
          style: { opacity: 0.9, direction: 180 },
        },
        {
          type: 'text',
          position: { x: 80, y: 1370, anchor: 'top-left' },
          size: { width: 600, height: 28 },
          style: { fontSize: 18, fontWeight: 'regular', textAlign: 'left', opacity: 0.5, letterSpacing: 3 },
          content: '{{musicType}}',
          toggleable: true,
          visible: true,
        },
        {
          type: 'text',
          position: { x: 80, y: 1405, anchor: 'top-left' },
          size: { width: 920, height: 72 },
          style: { fontSize: 60, fontWeight: 'black', textAlign: 'left' },
          content: '{{title}}',
        },
        {
          type: 'text',
          position: { x: 80, y: 1485, anchor: 'top-left' },
          size: { width: 920, height: 52 },
          style: { fontSize: 42, fontWeight: 'bold', textAlign: 'left' },
          content: '{{artistName}}',
          toggleable: true,
          visible: true,
        },
        {
          type: 'text',
          position: { x: 80, y: 1550, anchor: 'top-left' },
          size: { width: 600, height: 36 },
          style: { fontSize: 28, fontWeight: 'regular', textAlign: 'left', opacity: 0.8 },
          content: '{{releaseDate}}',
          toggleable: true,
          visible: true,
        },
      ],
    },
    {
      id: 'minimal',
      name: 'Minimal',
      defaultAlign: 'center',
      elements: [
        {
          type: 'artwork',
          position: { x: 240, y: 300, anchor: 'top-left' },
          size: { width: 600, height: 600 },
          style: { borderRadius: 8 },
        },
        {
          type: 'gradient',
          position: { x: 0, y: 0, anchor: 'top-left' },
          size: { width: 1080, height: 1920 },
          style: { opacity: 0.35, direction: 180 },
        },
        {
          type: 'text',
          position: { x: 540, y: 1000, anchor: 'top-center' },
          size: { width: 920, height: 28 },
          style: { fontSize: 18, fontWeight: 'regular', textAlign: 'center', opacity: 0.5, letterSpacing: 3 },
          content: '{{musicType}}',
          toggleable: true,
          visible: true,
        },
        {
          type: 'text',
          position: { x: 540, y: 1045, anchor: 'top-center' },
          size: { width: 920, height: 72 },
          style: { fontSize: 64, fontWeight: 'black', textAlign: 'center' },
          content: '{{title}}',
        },
        {
          type: 'text',
          position: { x: 540, y: 1130, anchor: 'top-center' },
          size: { width: 920, height: 52 },
          style: { fontSize: 44, fontWeight: 'bold', textAlign: 'center' },
          content: '{{artistName}}',
          toggleable: true,
          visible: true,
        },
        {
          type: 'text',
          position: { x: 540, y: 1200, anchor: 'top-center' },
          size: { width: 600, height: 36 },
          style: { fontSize: 28, fontWeight: 'regular', textAlign: 'center', opacity: 0.7 },
          content: '{{releaseDate}}',
          toggleable: true,
          visible: true,
        },
      ],
    },
    {
      id: 'split',
      name: 'Split',
      defaultAlign: 'center',
      elements: [
        {
          type: 'artwork',
          position: { x: 0, y: 0, anchor: 'top-left' },
          size: { width: 1080, height: 960 },
          style: { objectFit: 'cover' },
        },
        {
          type: 'gradient',
          position: { x: 0, y: 960, anchor: 'top-left' },
          size: { width: 1080, height: 960 },
          style: { opacity: 1, direction: 180 },
        },
        {
          type: 'text',
          position: { x: 540, y: 1120, anchor: 'top-center' },
          size: { width: 920, height: 28 },
          style: { fontSize: 18, fontWeight: 'regular', textAlign: 'center', opacity: 0.5, letterSpacing: 3 },
          content: '{{musicType}}',
          toggleable: true,
          visible: true,
        },
        {
          type: 'text',
          position: { x: 540, y: 1165, anchor: 'top-center' },
          size: { width: 920, height: 72 },
          style: { fontSize: 64, fontWeight: 'black', textAlign: 'center' },
          content: '{{title}}',
        },
        {
          type: 'text',
          position: { x: 540, y: 1255, anchor: 'top-center' },
          size: { width: 920, height: 52 },
          style: { fontSize: 44, fontWeight: 'bold', textAlign: 'center' },
          content: '{{artistName}}',
          toggleable: true,
          visible: true,
        },
        {
          type: 'text',
          position: { x: 540, y: 1325, anchor: 'top-center' },
          size: { width: 600, height: 36 },
          style: { fontSize: 28, fontWeight: 'regular', textAlign: 'center', opacity: 0.8 },
          content: '{{releaseDate}}',
          toggleable: true,
          visible: true,
        },
      ],
    },
  ],
}

export default igStory
