import type { AssetTemplate } from '@/types'

const igSquare: AssetTemplate = {
  id: 'ig-square',
  name: 'Instagram Square Post',
  platform: 'instagram',
  format: 'square',
  width: 1080,
  height: 1080,
  variants: [
    {
      id: 'centered',
      name: 'Centered',
      defaultAlign: 'center',
      elements: [
        {
          type: 'artwork',
          position: { x: 210, y: 90, anchor: 'top-center' },
          size: { width: 660, height: 660 },
          style: { borderRadius: 12 },
        },
        {
          type: 'gradient',
          position: { x: 0, y: 0, anchor: 'top-left' },
          size: { width: 1080, height: 1080 },
          style: { opacity: 0.6, direction: 180 },
        },
        {
          type: 'text',
          position: { x: 540, y: 770, anchor: 'top-center' },
          size: { width: 600, height: 24 },
          style: { fontSize: 14, fontWeight: 'regular', textAlign: 'center', opacity: 0.5, letterSpacing: 3 },
          content: '{{musicType}}',
          toggleable: true,
          visible: true,
        },
        {
          type: 'text',
          position: { x: 540, y: 800, anchor: 'top-center' },
          size: { width: 900, height: 56 },
          style: { fontSize: 50, fontWeight: 'black', textAlign: 'center' },
          content: '{{title}}',
        },
        {
          type: 'text',
          position: { x: 540, y: 862, anchor: 'top-center' },
          size: { width: 900, height: 48 },
          style: { fontSize: 40, fontWeight: 'bold', textAlign: 'center' },
          content: '{{artistName}}',
          toggleable: true,
          visible: true,
        },
        {
          type: 'text',
          position: { x: 540, y: 915, anchor: 'top-center' },
          size: { width: 600, height: 32 },
          style: { fontSize: 24, fontWeight: 'regular', textAlign: 'center', opacity: 0.8 },
          content: '{{releaseDate}}',
          toggleable: true,
          visible: true,
        },
      ],
    },
    {
      id: 'bottom-aligned',
      name: 'Bottom-aligned',
      defaultAlign: 'left',
      elements: [
        {
          type: 'artwork',
          position: { x: 0, y: 0, anchor: 'top-left' },
          size: { width: 1080, height: 1080 },
          style: { objectFit: 'cover' },
        },
        {
          type: 'gradient',
          position: { x: 0, y: 540, anchor: 'top-left' },
          size: { width: 1080, height: 540 },
          style: { opacity: 0.85, direction: 180 },
        },
        {
          type: 'text',
          position: { x: 60, y: 760, anchor: 'top-left' },
          size: { width: 600, height: 24 },
          style: { fontSize: 14, fontWeight: 'regular', textAlign: 'left', opacity: 0.5, letterSpacing: 3 },
          content: '{{musicType}}',
          toggleable: true,
          visible: true,
        },
        {
          type: 'text',
          position: { x: 60, y: 790, anchor: 'top-left' },
          size: { width: 960, height: 60 },
          style: { fontSize: 56, fontWeight: 'black', textAlign: 'left' },
          content: '{{title}}',
        },
        {
          type: 'text',
          position: { x: 60, y: 858, anchor: 'top-left' },
          size: { width: 960, height: 48 },
          style: { fontSize: 38, fontWeight: 'bold', textAlign: 'left' },
          content: '{{artistName}}',
          toggleable: true,
          visible: true,
        },
        {
          type: 'text',
          position: { x: 60, y: 908, anchor: 'top-left' },
          size: { width: 600, height: 32 },
          style: { fontSize: 26, fontWeight: 'regular', textAlign: 'left', opacity: 0.8 },
          content: '{{releaseDate}}',
          toggleable: true,
          visible: true,
        },
      ],
    },
    {
      id: 'split',
      name: 'Split',
      defaultAlign: 'center',
      elements: [
        {
          type: 'artwork',
          position: { x: 0, y: 0, anchor: 'top-left' },
          size: { width: 540, height: 1080 },
          style: { objectFit: 'cover' },
        },
        {
          type: 'gradient',
          position: { x: 540, y: 0, anchor: 'top-left' },
          size: { width: 540, height: 1080 },
          style: { opacity: 1, direction: 135 },
        },
        {
          type: 'text',
          position: { x: 810, y: 370, anchor: 'center' },
          size: { width: 400, height: 24 },
          style: { fontSize: 14, fontWeight: 'regular', textAlign: 'center', opacity: 0.5, letterSpacing: 3 },
          content: '{{musicType}}',
          toggleable: true,
          visible: true,
        },
        {
          type: 'text',
          position: { x: 810, y: 430, anchor: 'center' },
          size: { width: 460, height: 60 },
          style: { fontSize: 48, fontWeight: 'black', textAlign: 'center' },
          content: '{{title}}',
        },
        {
          type: 'text',
          position: { x: 810, y: 500, anchor: 'center' },
          size: { width: 460, height: 48 },
          style: { fontSize: 36, fontWeight: 'bold', textAlign: 'center' },
          content: '{{artistName}}',
          toggleable: true,
          visible: true,
        },
        {
          type: 'text',
          position: { x: 810, y: 565, anchor: 'center' },
          size: { width: 400, height: 32 },
          style: { fontSize: 24, fontWeight: 'regular', textAlign: 'center', opacity: 0.8 },
          content: '{{releaseDate}}',
          toggleable: true,
          visible: true,
        },
      ],
    },
    {
      id: 'minimal',
      name: 'Minimal',
      defaultAlign: 'center',
      elements: [
        {
          type: 'artwork',
          position: { x: 315, y: 150, anchor: 'top-left' },
          size: { width: 450, height: 450 },
          style: { borderRadius: 8 },
        },
        {
          type: 'gradient',
          position: { x: 0, y: 0, anchor: 'top-left' },
          size: { width: 1080, height: 1080 },
          style: { opacity: 0.35, direction: 180 },
        },
        {
          type: 'text',
          position: { x: 540, y: 660, anchor: 'top-center' },
          size: { width: 900, height: 24 },
          style: { fontSize: 14, fontWeight: 'regular', textAlign: 'center', opacity: 0.5, letterSpacing: 3 },
          content: '{{musicType}}',
          toggleable: true,
          visible: true,
        },
        {
          type: 'text',
          position: { x: 540, y: 705, anchor: 'top-center' },
          size: { width: 900, height: 64 },
          style: { fontSize: 54, fontWeight: 'black', textAlign: 'center' },
          content: '{{title}}',
        },
        {
          type: 'text',
          position: { x: 540, y: 780, anchor: 'top-center' },
          size: { width: 900, height: 48 },
          style: { fontSize: 38, fontWeight: 'bold', textAlign: 'center' },
          content: '{{artistName}}',
          toggleable: true,
          visible: true,
        },
        {
          type: 'text',
          position: { x: 540, y: 840, anchor: 'top-center' },
          size: { width: 600, height: 32 },
          style: { fontSize: 24, fontWeight: 'regular', textAlign: 'center', opacity: 0.7 },
          content: '{{releaseDate}}',
          toggleable: true,
          visible: true,
        },
      ],
    },
  ],
}

export default igSquare
