import type { AssetTemplate } from '@/types'

const pressHeader: AssetTemplate = {
  id: 'press-header',
  name: 'Press Kit Header',
  platform: 'general',
  format: 'header',
  width: 1600,
  height: 900,
  variants: [
    {
      id: 'elegant',
      name: 'Elegant',
      defaultAlign: 'center',
      elements: [
        {
          type: 'artwork',
          position: { x: 590, y: 60, anchor: 'top-left' },
          size: { width: 420, height: 420 },
          style: { borderRadius: 12 },
        },
        {
          type: 'gradient',
          position: { x: 0, y: 0, anchor: 'top-left' },
          size: { width: 1600, height: 900 },
          style: { opacity: 0.55, direction: 180 },
        },
        {
          type: 'text',
          position: { x: 800, y: 30, anchor: 'top-center' },
          size: { width: 200, height: 24 },
          style: { fontSize: 14, fontWeight: 'regular', textAlign: 'center', opacity: 0.5, letterSpacing: 3 },
          content: '{{musicType}}',
          toggleable: true,
          visible: true,
        },
        {
          type: 'text',
          position: { x: 800, y: 510, anchor: 'top-center' },
          size: { width: 1200, height: 58 },
          style: { fontSize: 48, fontWeight: 'bold', textAlign: 'center', letterSpacing: 2 },
          content: '{{title}}',
        },
        {
          type: 'text',
          position: { x: 800, y: 575, anchor: 'top-center' },
          size: { width: 1200, height: 40 },
          style: { fontSize: 32, fontWeight: 'regular', textAlign: 'center', letterSpacing: 4 },
          content: '{{artistName}}',
          toggleable: true,
          visible: true,
        },
        {
          type: 'text',
          position: { x: 800, y: 622, anchor: 'top-center' },
          size: { width: 600, height: 26 },
          style: { fontSize: 20, fontWeight: 'regular', textAlign: 'center', opacity: 0.7, letterSpacing: 2 },
          content: '{{releaseDate}}',
          toggleable: true,
          visible: true,
        },
      ],
    },
    {
      id: 'impact',
      name: 'Impact',
      defaultAlign: 'center',
      elements: [
        {
          type: 'artwork',
          position: { x: 0, y: 0, anchor: 'top-left' },
          size: { width: 1600, height: 900 },
          style: { objectFit: 'cover' },
        },
        {
          type: 'gradient',
          position: { x: 0, y: 0, anchor: 'top-left' },
          size: { width: 1600, height: 900 },
          style: { opacity: 0.75, direction: 180 },
        },
        {
          type: 'text',
          position: { x: 800, y: 250, anchor: 'center' },
          size: { width: 200, height: 24 },
          style: { fontSize: 16, fontWeight: 'regular', textAlign: 'center', opacity: 0.5, letterSpacing: 3 },
          content: '{{musicType}}',
          toggleable: true,
          visible: true,
        },
        {
          type: 'text',
          position: { x: 800, y: 340, anchor: 'center' },
          size: { width: 1400, height: 96 },
          style: { fontSize: 84, fontWeight: 'black', textAlign: 'center', textTransform: 'uppercase' },
          content: '{{title}}',
        },
        {
          type: 'text',
          position: { x: 800, y: 450, anchor: 'center' },
          size: { width: 1300, height: 56 },
          style: { fontSize: 48, fontWeight: 'bold', textAlign: 'center' },
          content: '{{artistName}}',
          toggleable: true,
          visible: true,
        },
        {
          type: 'text',
          position: { x: 800, y: 530, anchor: 'center' },
          size: { width: 600, height: 36 },
          style: { fontSize: 28, fontWeight: 'regular', textAlign: 'center', opacity: 0.8 },
          content: '{{releaseDate}}',
          toggleable: true,
          visible: true,
        },
      ],
    },
    {
      id: 'minimal',
      name: 'Minimal',
      defaultAlign: 'center',
      elements: [
        {
          type: 'artwork',
          position: { x: 600, y: 80, anchor: 'top-center' },
          size: { width: 380, height: 380 },
          style: { borderRadius: 8 },
        },
        {
          type: 'gradient',
          position: { x: 0, y: 0, anchor: 'top-left' },
          size: { width: 1600, height: 900 },
          style: { opacity: 0.35, direction: 180 },
        },
        {
          type: 'text',
          position: { x: 800, y: 490, anchor: 'top-center' },
          size: { width: 1200, height: 24 },
          style: { fontSize: 14, fontWeight: 'regular', textAlign: 'center', opacity: 0.5, letterSpacing: 3 },
          content: '{{musicType}}',
          toggleable: true,
          visible: true,
        },
        {
          type: 'text',
          position: { x: 800, y: 522, anchor: 'top-center' },
          size: { width: 1200, height: 58 },
          style: { fontSize: 48, fontWeight: 'black', textAlign: 'center' },
          content: '{{title}}',
        },
        {
          type: 'text',
          position: { x: 800, y: 585, anchor: 'top-center' },
          size: { width: 1200, height: 42 },
          style: { fontSize: 34, fontWeight: 'bold', textAlign: 'center' },
          content: '{{artistName}}',
          toggleable: true,
          visible: true,
        },
        {
          type: 'text',
          position: { x: 800, y: 635, anchor: 'top-center' },
          size: { width: 600, height: 28 },
          style: { fontSize: 22, fontWeight: 'regular', textAlign: 'center', opacity: 0.7 },
          content: '{{releaseDate}}',
          toggleable: true,
          visible: true,
        },
      ],
    },
    {
      id: 'split',
      name: 'Split',
      defaultAlign: 'center',
      elements: [
        {
          type: 'artwork',
          position: { x: 0, y: 0, anchor: 'top-left' },
          size: { width: 1600, height: 450 },
          style: { objectFit: 'cover' },
        },
        {
          type: 'gradient',
          position: { x: 0, y: 450, anchor: 'top-left' },
          size: { width: 1600, height: 450 },
          style: { opacity: 1, direction: 180 },
        },
        {
          type: 'text',
          position: { x: 800, y: 470, anchor: 'top-center' },
          size: { width: 200, height: 24 },
          style: { fontSize: 14, fontWeight: 'regular', textAlign: 'center', opacity: 0.5, letterSpacing: 3 },
          content: '{{musicType}}',
          toggleable: true,
          visible: true,
        },
        {
          type: 'text',
          position: { x: 800, y: 500, anchor: 'top-center' },
          size: { width: 1200, height: 58 },
          style: { fontSize: 48, fontWeight: 'black', textAlign: 'center' },
          content: '{{title}}',
        },
        {
          type: 'text',
          position: { x: 800, y: 565, anchor: 'top-center' },
          size: { width: 1200, height: 40 },
          style: { fontSize: 32, fontWeight: 'bold', textAlign: 'center' },
          content: '{{artistName}}',
          toggleable: true,
          visible: true,
        },
        {
          type: 'text',
          position: { x: 800, y: 610, anchor: 'top-center' },
          size: { width: 600, height: 28 },
          style: { fontSize: 22, fontWeight: 'regular', textAlign: 'center', opacity: 0.8 },
          content: '{{releaseDate}}',
          toggleable: true,
          visible: true,
        },
      ],
    },
    {
      id: 'full-bleed',
      name: 'Full Bleed',
      defaultAlign: 'center',
      elements: [
        {
          type: 'artwork',
          position: { x: 0, y: 0, anchor: 'top-left' },
          size: { width: 1600, height: 900 },
          style: { objectFit: 'cover' },
        },
        {
          type: 'gradient',
          position: { x: 0, y: 250, anchor: 'top-left' },
          size: { width: 1600, height: 650 },
          style: { opacity: 0.9, direction: 180 },
        },
        {
          type: 'text',
          position: { x: 800, y: 460, anchor: 'top-center' },
          size: { width: 200, height: 24 },
          style: { fontSize: 14, fontWeight: 'regular', textAlign: 'center', opacity: 0.5, letterSpacing: 3 },
          content: '{{musicType}}',
          toggleable: true,
          visible: true,
        },
        {
          type: 'text',
          position: { x: 800, y: 495, anchor: 'top-center' },
          size: { width: 1400, height: 64 },
          style: { fontSize: 54, fontWeight: 'black', textAlign: 'center' },
          content: '{{title}}',
        },
        {
          type: 'text',
          position: { x: 800, y: 570, anchor: 'top-center' },
          size: { width: 1300, height: 44 },
          style: { fontSize: 36, fontWeight: 'bold', textAlign: 'center' },
          content: '{{artistName}}',
          toggleable: true,
          visible: true,
        },
        {
          type: 'text',
          position: { x: 800, y: 625, anchor: 'top-center' },
          size: { width: 600, height: 28 },
          style: { fontSize: 24, fontWeight: 'regular', textAlign: 'center', opacity: 0.8 },
          content: '{{releaseDate}}',
          toggleable: true,
          visible: true,
        },
      ],
    },
  ],
}

export default pressHeader
