import type { AssetTemplate } from '@/types'

const twitterBanner: AssetTemplate = {
  id: 'twitter-banner',
  name: 'X/Twitter Banner',
  platform: 'twitter',
  format: 'banner',
  width: 1500,
  height: 500,
  variants: [
    {
      id: 'centered',
      name: 'Centered',
      defaultAlign: 'left',
      elements: [
        {
          type: 'artwork',
          position: { x: 420, y: 70, anchor: 'top-left' },
          size: { width: 320, height: 320 },
          style: { borderRadius: 10 },
        },
        {
          type: 'gradient',
          position: { x: 0, y: 0, anchor: 'top-left' },
          size: { width: 1500, height: 500 },
          style: { opacity: 0.6, direction: 90 },
        },
        {
          type: 'text',
          position: { x: 800, y: 110, anchor: 'top-left' },
          size: { width: 200, height: 20 },
          style: { fontSize: 13, fontWeight: 'regular', textAlign: 'left', opacity: 0.5, letterSpacing: 3 },
          content: '{{musicType}}',
          toggleable: true,
          visible: true,
        },
        {
          type: 'text',
          position: { x: 800, y: 145, anchor: 'top-left' },
          size: { width: 600, height: 52 },
          style: { fontSize: 44, fontWeight: 'black', textAlign: 'left' },
          content: '{{title}}',
        },
        {
          type: 'text',
          position: { x: 800, y: 215, anchor: 'top-left' },
          size: { width: 600, height: 36 },
          style: { fontSize: 28, fontWeight: 'bold', textAlign: 'left' },
          content: '{{artistName}}',
          toggleable: true,
          visible: true,
        },
        {
          type: 'text',
          position: { x: 800, y: 265, anchor: 'top-left' },
          size: { width: 400, height: 28 },
          style: { fontSize: 20, fontWeight: 'regular', textAlign: 'left', opacity: 0.8 },
          content: '{{releaseDate}}',
          toggleable: true,
          visible: true,
        },
      ],
    },
    {
      id: 'spread',
      name: 'Spread',
      defaultAlign: 'left',
      elements: [
        {
          type: 'artwork',
          position: { x: 50, y: 50, anchor: 'top-left' },
          size: { width: 400, height: 400 },
          style: { objectFit: 'cover', borderRadius: 8 },
        },
        {
          type: 'gradient',
          position: { x: 0, y: 0, anchor: 'top-left' },
          size: { width: 1500, height: 500 },
          style: { opacity: 0.7, direction: 90 },
        },
        {
          type: 'text',
          position: { x: 520, y: 140, anchor: 'top-left' },
          size: { width: 200, height: 20 },
          style: { fontSize: 14, fontWeight: 'regular', textAlign: 'left', opacity: 0.5, letterSpacing: 3 },
          content: '{{musicType}}',
          toggleable: true,
          visible: true,
        },
        {
          type: 'text',
          position: { x: 520, y: 180, anchor: 'top-left' },
          size: { width: 600, height: 52 },
          style: { fontSize: 46, fontWeight: 'black', textAlign: 'left' },
          content: '{{title}}',
        },
        {
          type: 'text',
          position: { x: 520, y: 255, anchor: 'top-left' },
          size: { width: 600, height: 36 },
          style: { fontSize: 28, fontWeight: 'bold', textAlign: 'left' },
          content: '{{artistName}}',
          toggleable: true,
          visible: true,
        },
        {
          type: 'text',
          position: { x: 520, y: 305, anchor: 'top-left' },
          size: { width: 400, height: 28 },
          style: { fontSize: 22, fontWeight: 'regular', textAlign: 'left', opacity: 0.8 },
          content: '{{releaseDate}}',
          toggleable: true,
          visible: true,
        },
      ],
    },
  ],
}

export default twitterBanner
