import type { AssetTemplate } from '@/types'

const twitterPost: AssetTemplate = {
  id: 'twitter-post',
  name: 'X/Twitter Post',
  platform: 'twitter',
  format: 'post',
  width: 1200,
  height: 675,
  variants: [
    {
      id: 'centered',
      name: 'Centered',
      defaultAlign: 'left',
      elements: [
        {
          type: 'artwork',
          position: { x: 50, y: 88, anchor: 'top-left' },
          size: { width: 480, height: 500 },
          style: { borderRadius: 10 },
        },
        {
          type: 'gradient',
          position: { x: 0, y: 0, anchor: 'top-left' },
          size: { width: 1200, height: 675 },
          style: { opacity: 0.65, direction: 180 },
        },
        {
          type: 'text',
          position: { x: 620, y: 195, anchor: 'top-left' },
          size: { width: 520, height: 20 },
          style: { fontSize: 14, fontWeight: 'regular', textAlign: 'left', opacity: 0.5, letterSpacing: 3 },
          content: '{{musicType}}',
          toggleable: true,
          visible: true,
        },
        {
          type: 'text',
          position: { x: 620, y: 228, anchor: 'top-left' },
          size: { width: 520, height: 50 },
          style: { fontSize: 44, fontWeight: 'black', textAlign: 'left' },
          content: '{{title}}',
        },
        {
          type: 'text',
          position: { x: 620, y: 300, anchor: 'top-left' },
          size: { width: 520, height: 36 },
          style: { fontSize: 30, fontWeight: 'bold', textAlign: 'left' },
          content: '{{artistName}}',
          toggleable: true,
          visible: true,
        },
        {
          type: 'text',
          position: { x: 620, y: 352, anchor: 'top-left' },
          size: { width: 400, height: 28 },
          style: { fontSize: 22, fontWeight: 'regular', textAlign: 'left', opacity: 0.8 },
          content: '{{releaseDate}}',
          toggleable: true,
          visible: true,
        },
      ],
    },
    {
      id: 'left-aligned',
      name: 'Left-aligned',
      defaultAlign: 'left',
      elements: [
        {
          type: 'artwork',
          position: { x: 650, y: 88, anchor: 'top-left' },
          size: { width: 500, height: 500 },
          style: { objectFit: 'cover', borderRadius: 8 },
        },
        {
          type: 'gradient',
          position: { x: 0, y: 0, anchor: 'top-left' },
          size: { width: 700, height: 675 },
          style: { opacity: 0.8, direction: 90 },
        },
        {
          type: 'text',
          position: { x: 60, y: 200, anchor: 'top-left' },
          size: { width: 200, height: 20 },
          style: { fontSize: 14, fontWeight: 'regular', textAlign: 'left', opacity: 0.5, letterSpacing: 3 },
          content: '{{musicType}}',
          toggleable: true,
          visible: true,
        },
        {
          type: 'text',
          position: { x: 60, y: 240, anchor: 'top-left' },
          size: { width: 480, height: 56 },
          style: { fontSize: 48, fontWeight: 'black', textAlign: 'left' },
          content: '{{title}}',
        },
        {
          type: 'text',
          position: { x: 60, y: 320, anchor: 'top-left' },
          size: { width: 480, height: 36 },
          style: { fontSize: 30, fontWeight: 'bold', textAlign: 'left' },
          content: '{{artistName}}',
          toggleable: true,
          visible: true,
        },
        {
          type: 'text',
          position: { x: 60, y: 370, anchor: 'top-left' },
          size: { width: 400, height: 28 },
          style: { fontSize: 22, fontWeight: 'regular', textAlign: 'left', opacity: 0.8 },
          content: '{{releaseDate}}',
          toggleable: true,
          visible: true,
        },
      ],
    },
    {
      id: 'minimal',
      name: 'Minimal',
      defaultAlign: 'left',
      elements: [
        {
          type: 'artwork',
          position: { x: 60, y: 138, anchor: 'top-left' },
          size: { width: 400, height: 400 },
          style: { borderRadius: 8 },
        },
        {
          type: 'gradient',
          position: { x: 0, y: 0, anchor: 'top-left' },
          size: { width: 1200, height: 675 },
          style: { opacity: 0.4, direction: 90 },
        },
        {
          type: 'text',
          position: { x: 540, y: 80, anchor: 'top-left' },
          size: { width: 200, height: 20 },
          style: { fontSize: 14, fontWeight: 'regular', textAlign: 'left', opacity: 0.5, letterSpacing: 3 },
          content: '{{musicType}}',
          toggleable: true,
          visible: true,
        },
        {
          type: 'text',
          position: { x: 540, y: 120, anchor: 'top-left' },
          size: { width: 600, height: 52 },
          style: { fontSize: 44, fontWeight: 'black', textAlign: 'left' },
          content: '{{title}}',
        },
        {
          type: 'text',
          position: { x: 540, y: 185, anchor: 'top-left' },
          size: { width: 600, height: 34 },
          style: { fontSize: 28, fontWeight: 'bold', textAlign: 'left' },
          content: '{{artistName}}',
          toggleable: true,
          visible: true,
        },
        {
          type: 'text',
          position: { x: 540, y: 230, anchor: 'top-left' },
          size: { width: 400, height: 26 },
          style: { fontSize: 20, fontWeight: 'regular', textAlign: 'left', opacity: 0.7 },
          content: '{{releaseDate}}',
          toggleable: true,
          visible: true,
        },
      ],
    },
    {
      id: 'split',
      name: 'Split',
      defaultAlign: 'center',
      elements: [
        {
          type: 'artwork',
          position: { x: 0, y: 0, anchor: 'top-left' },
          size: { width: 1200, height: 340 },
          style: { objectFit: 'cover' },
        },
        {
          type: 'gradient',
          position: { x: 0, y: 340, anchor: 'top-left' },
          size: { width: 1200, height: 335 },
          style: { opacity: 1, direction: 180 },
        },
        {
          type: 'text',
          position: { x: 600, y: 430, anchor: 'center' },
          size: { width: 200, height: 20 },
          style: { fontSize: 14, fontWeight: 'regular', textAlign: 'center', opacity: 0.5, letterSpacing: 3 },
          content: '{{musicType}}',
          toggleable: true,
          visible: true,
        },
        {
          type: 'text',
          position: { x: 600, y: 485, anchor: 'center' },
          size: { width: 1000, height: 50 },
          style: { fontSize: 42, fontWeight: 'black', textAlign: 'center' },
          content: '{{title}}',
        },
        {
          type: 'text',
          position: { x: 600, y: 550, anchor: 'center' },
          size: { width: 800, height: 34 },
          style: { fontSize: 28, fontWeight: 'bold', textAlign: 'center' },
          content: '{{artistName}}',
          toggleable: true,
          visible: true,
        },
        {
          type: 'text',
          position: { x: 600, y: 600, anchor: 'center' },
          size: { width: 500, height: 26 },
          style: { fontSize: 20, fontWeight: 'regular', textAlign: 'center', opacity: 0.8 },
          content: '{{releaseDate}}',
          toggleable: true,
          visible: true,
        },
      ],
    },
  ],
}

export default twitterPost
