import type { AssetTemplate } from '@/types'

const ytThumb: AssetTemplate = {
  id: 'yt-thumb',
  name: 'YouTube Thumbnail',
  platform: 'youtube',
  format: 'thumbnail',
  width: 1280,
  height: 720,
  variants: [
    {
      id: 'bold',
      name: 'Bold',
      defaultAlign: 'center',
      elements: [
        {
          type: 'artwork',
          position: { x: 0, y: 0, anchor: 'top-left' },
          size: { width: 1280, height: 720 },
          style: { objectFit: 'cover' },
        },
        {
          type: 'gradient',
          position: { x: 0, y: 0, anchor: 'top-left' },
          size: { width: 1280, height: 720 },
          style: { opacity: 0.7, direction: 180 },
        },
        {
          type: 'text',
          position: { x: 640, y: 220, anchor: 'center' },
          size: { width: 200, height: 24 },
          style: { fontSize: 16, fontWeight: 'regular', textAlign: 'center', opacity: 0.5, letterSpacing: 3 },
          content: '{{musicType}}',
          toggleable: true,
          visible: true,
        },
        {
          type: 'text',
          position: { x: 640, y: 300, anchor: 'center' },
          size: { width: 1100, height: 80 },
          style: { fontSize: 72, fontWeight: 'black', textAlign: 'center', textTransform: 'uppercase' },
          content: '{{title}}',
        },
        {
          type: 'text',
          position: { x: 640, y: 390, anchor: 'center' },
          size: { width: 1000, height: 52 },
          style: { fontSize: 46, fontWeight: 'bold', textAlign: 'center' },
          content: '{{artistName}}',
          toggleable: true,
          visible: true,
        },
        {
          type: 'text',
          position: { x: 640, y: 460, anchor: 'center' },
          size: { width: 500, height: 32 },
          style: { fontSize: 26, fontWeight: 'regular', textAlign: 'center', opacity: 0.8 },
          content: '{{releaseDate}}',
          toggleable: true,
          visible: true,
        },
      ],
    },
    {
      id: 'clean',
      name: 'Clean',
      defaultAlign: 'left',
      elements: [
        {
          type: 'artwork',
          position: { x: 40, y: 110, anchor: 'top-left' },
          size: { width: 500, height: 500 },
          style: { borderRadius: 12 },
        },
        {
          type: 'gradient',
          position: { x: 0, y: 0, anchor: 'top-left' },
          size: { width: 1280, height: 720 },
          style: { opacity: 0.6, direction: 90 },
        },
        {
          type: 'text',
          position: { x: 700, y: 220, anchor: 'top-left' },
          size: { width: 200, height: 20 },
          style: { fontSize: 14, fontWeight: 'regular', textAlign: 'left', opacity: 0.5, letterSpacing: 3 },
          content: '{{musicType}}',
          toggleable: true,
          visible: true,
        },
        {
          type: 'text',
          position: { x: 700, y: 260, anchor: 'top-left' },
          size: { width: 520, height: 60 },
          style: { fontSize: 52, fontWeight: 'black', textAlign: 'left' },
          content: '{{title}}',
        },
        {
          type: 'text',
          position: { x: 700, y: 340, anchor: 'top-left' },
          size: { width: 520, height: 40 },
          style: { fontSize: 34, fontWeight: 'bold', textAlign: 'left' },
          content: '{{artistName}}',
          toggleable: true,
          visible: true,
        },
        {
          type: 'text',
          position: { x: 700, y: 400, anchor: 'top-left' },
          size: { width: 400, height: 28 },
          style: { fontSize: 24, fontWeight: 'regular', textAlign: 'left', opacity: 0.8 },
          content: '{{releaseDate}}',
          toggleable: true,
          visible: true,
        },
      ],
    },
    {
      id: 'split',
      name: 'Split',
      defaultAlign: 'center',
      elements: [
        {
          type: 'artwork',
          position: { x: 0, y: 0, anchor: 'top-left' },
          size: { width: 1280, height: 360 },
          style: { objectFit: 'cover' },
        },
        {
          type: 'gradient',
          position: { x: 0, y: 360, anchor: 'top-left' },
          size: { width: 1280, height: 360 },
          style: { opacity: 1, direction: 180 },
        },
        {
          type: 'text',
          position: { x: 640, y: 445, anchor: 'center' },
          size: { width: 200, height: 20 },
          style: { fontSize: 14, fontWeight: 'regular', textAlign: 'center', opacity: 0.5, letterSpacing: 3 },
          content: '{{musicType}}',
          toggleable: true,
          visible: true,
        },
        {
          type: 'text',
          position: { x: 640, y: 505, anchor: 'center' },
          size: { width: 1100, height: 56 },
          style: { fontSize: 48, fontWeight: 'black', textAlign: 'center' },
          content: '{{title}}',
        },
        {
          type: 'text',
          position: { x: 640, y: 575, anchor: 'center' },
          size: { width: 900, height: 36 },
          style: { fontSize: 30, fontWeight: 'bold', textAlign: 'center' },
          content: '{{artistName}}',
          toggleable: true,
          visible: true,
        },
        {
          type: 'text',
          position: { x: 640, y: 630, anchor: 'center' },
          size: { width: 500, height: 28 },
          style: { fontSize: 22, fontWeight: 'regular', textAlign: 'center', opacity: 0.8 },
          content: '{{releaseDate}}',
          toggleable: true,
          visible: true,
        },
      ],
    },
    {
      id: 'minimal',
      name: 'Minimal',
      defaultAlign: 'left',
      elements: [
        {
          type: 'artwork',
          position: { x: 60, y: 160, anchor: 'top-left' },
          size: { width: 400, height: 400 },
          style: { borderRadius: 8 },
        },
        {
          type: 'gradient',
          position: { x: 0, y: 0, anchor: 'top-left' },
          size: { width: 1280, height: 720 },
          style: { opacity: 0.4, direction: 90 },
        },
        {
          type: 'text',
          position: { x: 560, y: 120, anchor: 'top-left' },
          size: { width: 200, height: 20 },
          style: { fontSize: 14, fontWeight: 'regular', textAlign: 'left', opacity: 0.5, letterSpacing: 3 },
          content: '{{musicType}}',
          toggleable: true,
          visible: true,
        },
        {
          type: 'text',
          position: { x: 560, y: 160, anchor: 'top-left' },
          size: { width: 640, height: 56 },
          style: { fontSize: 48, fontWeight: 'black', textAlign: 'left' },
          content: '{{title}}',
        },
        {
          type: 'text',
          position: { x: 560, y: 235, anchor: 'top-left' },
          size: { width: 640, height: 36 },
          style: { fontSize: 30, fontWeight: 'bold', textAlign: 'left' },
          content: '{{artistName}}',
          toggleable: true,
          visible: true,
        },
        {
          type: 'text',
          position: { x: 560, y: 285, anchor: 'top-left' },
          size: { width: 400, height: 28 },
          style: { fontSize: 22, fontWeight: 'regular', textAlign: 'left', opacity: 0.7 },
          content: '{{releaseDate}}',
          toggleable: true,
          visible: true,
        },
      ],
    },
  ],
}

export default ytThumb
